version: "3"

services:
  sr:
    image: bennysobol/sr:latest
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - C:/Users/BennySobol/OneDrive/Desktop/dataset:/home/user/dataset
      - C:/Users/BennySobol/OneDrive/Desktop/Sr:/home/user/benny/Sr
    network_mode: host
    